<?php

namespace App\Console\Commands;

use App\Contracts\GameHandler;
use App\GameManager;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class GenerateGameTypesCommand extends Command
{
    protected $signature = 'game:generate-types {--path=resources/js/types/generated.d.ts : Output path}';

    protected $description = 'Generate TypeScript types from game handler schemas (discriminated union Server type)';

    /**
     * Map of schema field types to TypeScript types.
     *
     * @var array<string, string>
     */
    private const FIELD_TYPE_MAP = [
        'toggle' => 'boolean',
        'number' => 'number',
        'text' => 'string',
        'textarea' => 'string',
        'segmented' => 'number',
        'custom' => 'string | null',
    ];

    public function handle(GameManager $gameManager): int
    {
        $handlers = $gameManager->allHandlers();
        $lines = [];

        $lines[] = '/**';
        $lines[] = ' * AUTO-GENERATED by `php artisan game:generate-types`';
        $lines[] = ' * DO NOT EDIT MANUALLY — changes will be overwritten.';
        $lines[] = ' *';
        $lines[] = ' * Regenerate with: php artisan game:generate-types';
        $lines[] = ' */';
        $lines[] = '';
        $lines[] = "import type { GameInstall, ModPreset, ServerBackup } from './game';";
        $lines[] = '';

        // Collect per-handler data
        $serverVariants = [];
        $settingsTypes = [];

        foreach ($handlers as $handler) {
            $value = $handler->value();
            $schema = $handler->settingsSchema();
            $settingsRelation = $handler->settingsRelationName();

            // Extract fields grouped by source
            $fieldsBySource = $this->extractFieldsBySource($schema);

            // Generate settings interface if this handler has a settings model
            if ($settingsRelation !== null) {
                $settingsSource = $this->settingsSourceName($handler);
                $settingsTypeName = $this->settingsTypeName($handler);

                $settingsFields = $fieldsBySource[$settingsSource] ?? [];

                if (! empty($settingsFields)) {
                    $settingsTypes[$settingsTypeName] = $settingsFields;
                }

                // Build the server variant with the settings relationship
                $serverVariants[] = [
                    'gameType' => $value,
                    'typeName' => $this->serverVariantName($handler),
                    'settingsRelation' => $settingsRelation,
                    'settingsType' => $settingsTypeName,
                    'hasSettings' => ! empty($settingsFields),
                ];
            } else {
                $serverVariants[] = [
                    'gameType' => $value,
                    'typeName' => $this->serverVariantName($handler),
                    'settingsRelation' => null,
                    'settingsType' => null,
                    'hasSettings' => false,
                ];
            }
        }

        // Emit the ServerBase type
        $lines[] = $this->generateServerBase();

        // Emit settings types
        foreach ($settingsTypes as $typeName => $fields) {
            $lines[] = $this->generateSettingsType($typeName, $fields);
        }

        // Emit server variants
        foreach ($serverVariants as $variant) {
            $lines[] = $this->generateServerVariant($variant);
        }

        // Emit the discriminated union
        $variantNames = array_map(fn (array $v) => $v['typeName'], $serverVariants);
        $lines[] = 'export type Server = '.implode(' | ', $variantNames).';';
        $lines[] = '';

        $output = implode("\n", $lines);
        $path = base_path($this->option('path'));

        $dir = dirname($path);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($path, $output);

        $this->components->info(sprintf(
            'Generated %d game type(s) to [%s].',
            count($serverVariants),
            $this->option('path'),
        ));

        return self::SUCCESS;
    }

    /**
     * Extract all non-separator fields from the schema, grouped by their effective source.
     *
     * @param  list<array<string, mixed>>  $schema
     * @return array<string, list<array{key: string, tsType: string}>>
     */
    private function extractFieldsBySource(array $schema): array
    {
        $fieldsBySource = [];

        foreach ($schema as $section) {
            $sectionSource = $section['source'] ?? 'server';

            $allFields = [];
            if (! empty($section['fields'])) {
                $allFields = array_merge($allFields, $section['fields']);
            }
            if (! empty($section['groups'])) {
                foreach ($section['groups'] as $group) {
                    $allFields = array_merge($allFields, $group['fields']);
                }
            }

            foreach ($allFields as $field) {
                $type = $field['type'] ?? null;
                $key = $field['key'] ?? null;

                if ($key === null || $type === 'separator') {
                    continue;
                }

                $source = $field['source'] ?? $sectionSource;
                $tsType = $this->resolveFieldTsType($field);

                $fieldsBySource[$source][] = [
                    'key' => $key,
                    'tsType' => $tsType,
                ];
            }
        }

        return $fieldsBySource;
    }

    /**
     * Resolve the TypeScript type for a schema field.
     */
    private function resolveFieldTsType(array $field): string
    {
        $type = $field['type'];

        // storeAsString overrides number → string
        if ($type === 'number' && ! empty($field['storeAsString'])) {
            return 'string';
        }

        return self::FIELD_TYPE_MAP[$type] ?? 'unknown';
    }

    /**
     * Derive the source key for settings fields (e.g., 'arma3_settings').
     */
    private function settingsSourceName(GameHandler $handler): string
    {
        $relation = $handler->settingsRelationName();

        return Str::snake($relation);
    }

    /**
     * PascalCase type name for a handler's settings (e.g., 'Arma3Settings').
     */
    private function settingsTypeName(GameHandler $handler): string
    {
        return Str::studly($handler->settingsRelationName());
    }

    /**
     * PascalCase variant name for the server union (e.g., 'Arma3Server').
     */
    private function serverVariantName(GameHandler $handler): string
    {
        return Str::studly($handler->value()).'Server';
    }

    /**
     * Generate the ServerBase type containing all shared server fields.
     */
    private function generateServerBase(): string
    {
        return <<<'TS'
export type ServerBase = {
    id: number;
    game_type: string;
    name: string;
    port: number;
    query_port: number;
    max_players: number;
    password: string | null;
    admin_password: string | null;
    description: string | null;
    active_preset_id: number | null;
    game_install_id: number | null;
    status: import('./game').ServerStatus;
    auto_restart: boolean;
    additional_params: string | null;
    verify_signatures: boolean;
    allowed_file_patching: boolean;
    battle_eye: boolean;
    persistent: boolean;
    von_enabled: boolean;
    additional_server_options: string | null;
    supports_backups?: boolean;
    profiles_path?: string;
    created_at: string;
    updated_at: string;
    game_install?: GameInstall;
    active_preset?: ModPreset;
    backups?: ServerBackup[];
};

TS;
    }

    /**
     * Generate a settings interface from extracted fields.
     *
     * @param  list<array{key: string, tsType: string}>  $fields
     */
    private function generateSettingsType(string $typeName, array $fields): string
    {
        $lines = ["export type {$typeName} = {"];
        $lines[] = '    id: number;';
        $lines[] = '    server_id: number;';

        // Deduplicate fields (same key may appear in multiple sections)
        $seen = ['id' => true, 'server_id' => true];
        foreach ($fields as $field) {
            if (isset($seen[$field['key']])) {
                continue;
            }
            $seen[$field['key']] = true;
            $lines[] = "    {$field['key']}: {$field['tsType']};";
        }

        $lines[] = '};';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate a server variant type for the discriminated union.
     *
     * @param  array{gameType: string, typeName: string, settingsRelation: ?string, settingsType: ?string, hasSettings: bool}  $variant
     */
    private function generateServerVariant(array $variant): string
    {
        $lines = ["export type {$variant['typeName']} = ServerBase & {"];
        $lines[] = "    game_type: '{$variant['gameType']}';";

        if ($variant['hasSettings'] && $variant['settingsRelation'] !== null) {
            $snakeRelation = Str::snake($variant['settingsRelation']);
            $lines[] = "    {$snakeRelation}?: {$variant['settingsType']};";
        }

        $lines[] = '};';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
