services:
  armaani:
    build: .
    container_name: armaani
    network_mode: host
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS:-:80}
    restart: unless-stopped
