/**
 * AUTO-GENERATED by `php artisan game:generate-types`
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * Regenerate with: php artisan game:generate-types
 */

import type { GameInstall, ModPreset, ServerBackup, ServerStatus } from './game';

export type ServerBase = {
    id: number;
    game_type: string;
    name: string;
    port: number;
    query_port: number | null;
    max_players: number;
    password: string | null;
    description: string | null;
    active_preset_id: number | null;
    game_install_id: number | null;
    status: ServerStatus;
    auto_restart: boolean;
    additional_params: string | null;
    supports_backups?: boolean;
    profiles_path?: string;
    created_at: string;
    updated_at: string;
    game_install?: GameInstall;
    active_preset?: ModPreset;
    backups?: ServerBackup[];
};

export type Arma3Settings = {
    id: number;
    server_id: number;
    admin_password: string;
    verify_signatures: boolean;
    allowed_file_patching: boolean;
    battle_eye: boolean;
    von_enabled: boolean;
    persistent: boolean;
    reduced_damage: boolean;
    stamina_bar: boolean;
    weapon_crosshair: boolean;
    vision_aid: boolean;
    camera_shake: boolean;
    score_table: boolean;
    death_messages: boolean;
    von_id: boolean;
    map_content: boolean;
    auto_report: boolean;
    group_indicators: number;
    friendly_tags: number;
    enemy_tags: number;
    detected_mines: number;
    ai_level_preset: number;
    skill_ai: string;
    precision_ai: string;
    commands: number;
    waypoints: number;
    weapon_info: number;
    stance_indicator: number;
    third_person_view: number;
    tactical_ping: number;
    max_msg_send: number;
    max_size_guaranteed: number;
    max_size_nonguaranteed: number;
    min_bandwidth: string;
    max_bandwidth: string;
    min_error_to_send: string;
    min_error_to_send_near: string;
    max_packet_size: number;
    max_custom_file_size: number;
    view_distance: number;
    terrain_grid: string;
    additional_server_options: string;
};

export type FactorioSettings = {
    id: number;
    server_id: number;
    rcon_password: string;
    visibility_public: boolean;
    visibility_lan: boolean;
    require_user_verification: boolean;
    max_upload_kbps: number;
    max_heartbeats_per_second: number;
    ignore_player_limit_for_returning: boolean;
    allow_commands: number;
    autosave_interval: number;
    autosave_slots: number;
    afk_autokick_interval: number;
    auto_pause: boolean;
    only_admins_can_pause: boolean;
    autosave_only_on_server: boolean;
    non_blocking_saving: boolean;
    tags: string;
    coal_frequency: number;
    coal_size: number;
    coal_richness: number;
    copper_ore_frequency: number;
    copper_ore_size: number;
    copper_ore_richness: number;
    crude_oil_frequency: number;
    crude_oil_size: number;
    crude_oil_richness: number;
    iron_ore_frequency: number;
    iron_ore_size: number;
    iron_ore_richness: number;
    stone_frequency: number;
    stone_size: number;
    stone_richness: number;
    trees_frequency: number;
    trees_size: number;
    trees_richness: number;
    uranium_ore_frequency: number;
    uranium_ore_size: number;
    uranium_ore_richness: number;
    enemy_base_frequency: number;
    enemy_base_size: number;
    enemy_base_richness: number;
    map_width: number;
    map_height: number;
    starting_area: number;
    water: number;
    terrain_segmentation: number;
    cliff_elevation_0: number;
    cliff_elevation_interval: number;
    cliff_richness: number;
    peaceful_mode: boolean;
    map_seed: string;
    pollution_enabled: boolean;
    evolution_enabled: boolean;
    evolution_time_factor: number;
    evolution_destroy_factor: number;
    evolution_pollution_factor: number;
    expansion_enabled: boolean;
};

export type ProjectzomboidSettings = {
    id: number;
    server_id: number;
    admin_password: string;
    open: boolean;
    pvp: boolean;
    pause_empty: boolean;
    global_chat: boolean;
    safety_system: boolean;
    show_safety: boolean;
    map: string;
    sleep_allowed: boolean;
    sleep_needed: boolean;
    announce_death: boolean;
    do_lua_checksum: boolean;
    max_accounts_per_user: number;
    login_queue_enabled: boolean;
    deny_login_on_overloaded_server: boolean;
};

export type ReforgerSettings = {
    id: number;
    server_id: number;
    scenario_id: string | null;
    admin_password: string;
    third_person_view_enabled: boolean;
    battle_eye: boolean;
    cross_platform: boolean;
    max_fps: number;
};

export type Arma3Server = ServerBase & {
    game_type: 'arma3';
    arma3_settings?: Arma3Settings;
};

export type DayzServer = ServerBase & {
    game_type: 'dayz';
};

export type FactorioServer = ServerBase & {
    game_type: 'factorio';
    factorio_settings?: FactorioSettings;
};

export type ProjectzomboidServer = ServerBase & {
    game_type: 'projectzomboid';
    projectzomboid_settings?: ProjectzomboidSettings;
};

export type ReforgerServer = ServerBase & {
    game_type: 'reforger';
    reforger_settings?: ReforgerSettings;
};

export type Server = Arma3Server | DayzServer | FactorioServer | ProjectzomboidServer | ReforgerServer;
