/**
 * AUTO-GENERATED by `php artisan game:generate-types`
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * Regenerate with: php artisan game:generate-types
 */

import type { GameInstall, ModPreset, ServerBackup } from './game';

export type ServerBase = {
    id: number;
    game_type: string;
    name: string;
    port: number;
    query_port: number;
    max_players: number;
    password: string | null;
    admin_password: string | null;
    description: string | null;
    active_preset_id: number | null;
    game_install_id: number | null;
    status: import('./game').ServerStatus;
    auto_restart: boolean;
    additional_params: string | null;
    verify_signatures: boolean;
    allowed_file_patching: boolean;
    battle_eye: boolean;
    persistent: boolean;
    von_enabled: boolean;
    additional_server_options: string | null;
    supports_backups?: boolean;
    profiles_path?: string;
    created_at: string;
    updated_at: string;
    game_install?: GameInstall;
    active_preset?: ModPreset;
    backups?: ServerBackup[];
};

export type Arma3Settings = {
    id: number;
    server_id: number;
    reduced_damage: boolean;
    stamina_bar: boolean;
    weapon_crosshair: boolean;
    vision_aid: boolean;
    camera_shake: boolean;
    score_table: boolean;
    death_messages: boolean;
    von_id: boolean;
    map_content: boolean;
    auto_report: boolean;
    group_indicators: number;
    friendly_tags: number;
    enemy_tags: number;
    detected_mines: number;
    ai_level_preset: number;
    skill_ai: string;
    precision_ai: string;
    commands: number;
    waypoints: number;
    weapon_info: number;
    stance_indicator: number;
    third_person_view: number;
    tactical_ping: number;
    max_msg_send: number;
    max_size_guaranteed: number;
    max_size_nonguaranteed: number;
    min_bandwidth: string;
    max_bandwidth: string;
    min_error_to_send: string;
    min_error_to_send_near: string;
    max_packet_size: number;
    max_custom_file_size: number;
    view_distance: number;
    terrain_grid: string;
};

export type ReforgerSettings = {
    id: number;
    server_id: number;
    scenario_id: string | null;
    third_person_view_enabled: boolean;
    cross_platform: boolean;
    max_fps: number;
};

export type Arma3Server = ServerBase & {
    game_type: 'arma3';
    arma3_settings?: Arma3Settings;
};

export type DayzServer = ServerBase & {
    game_type: 'dayz';
};

export type ReforgerServer = ServerBase & {
    game_type: 'reforger';
    reforger_settings?: ReforgerSettings;
};

export type Server = Arma3Server | DayzServer | ReforgerServer;
